// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: containers.sql

package sqlcdb

import (
	"context"

	uuid "github.com/google/uuid"
)

const createContainer = `-- name: CreateContainer :one
INSERT INTO evidence_containers (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at
`

type CreateContainerParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateContainer(ctx context.Context, arg CreateContainerParams) (EvidenceContainer, error) {
	row := q.db.QueryRow(ctx, createContainer, arg.UserID, arg.Name)
	var i EvidenceContainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContainer = `-- name: DeleteContainer :exec
DELETE FROM evidence_containers
WHERE id = $1 AND user_id = $2
`

type DeleteContainerParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteContainer(ctx context.Context, arg DeleteContainerParams) error {
	_, err := q.db.Exec(ctx, deleteContainer, arg.ID, arg.UserID)
	return err
}

const getContainerByID = `-- name: GetContainerByID :one
SELECT id, user_id, name, created_at FROM evidence_containers
WHERE id = $1
`

func (q *Queries) GetContainerByID(ctx context.Context, id uuid.UUID) (EvidenceContainer, error) {
	row := q.db.QueryRow(ctx, getContainerByID, id)
	var i EvidenceContainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listContainersByUser = `-- name: ListContainersByUser :many
SELECT id, user_id, name, created_at FROM evidence_containers
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListContainersByUser(ctx context.Context, userID uuid.UUID) ([]EvidenceContainer, error) {
	rows, err := q.db.Query(ctx, listContainersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvidenceContainer
	for rows.Next() {
		var i EvidenceContainer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
