// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: evidence.sql

package sqlcdb

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvidence = `-- name: CreateEvidence :one
INSERT INTO evidence (user_id, filename, original_name, mime_type, file_size, description, latitude, longitude)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, filename, original_name, mime_type, file_size, description, latitude, longitude, created_at
`

type CreateEvidenceParams struct {
	UserID       uuid.UUID     `json:"user_id"`
	Filename     string        `json:"filename"`
	OriginalName string        `json:"original_name"`
	MimeType     string        `json:"mime_type"`
	FileSize     int64         `json:"file_size"`
	Description  pgtype.Text   `json:"description"`
	Latitude     pgtype.Float8 `json:"latitude"`
	Longitude    pgtype.Float8 `json:"longitude"`
}

func (q *Queries) CreateEvidence(ctx context.Context, arg CreateEvidenceParams) (Evidence, error) {
	row := q.db.QueryRow(ctx, createEvidence,
		arg.UserID,
		arg.Filename,
		arg.OriginalName,
		arg.MimeType,
		arg.FileSize,
		arg.Description,
		arg.Latitude,
		arg.Longitude,
	)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSize,
		&i.Description,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEvidence = `-- name: DeleteEvidence :exec
DELETE FROM evidence
WHERE id = $1 AND user_id = $2
`

type DeleteEvidenceParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteEvidence(ctx context.Context, arg DeleteEvidenceParams) error {
	_, err := q.db.Exec(ctx, deleteEvidence, arg.ID, arg.UserID)
	return err
}

const getEvidenceByID = `-- name: GetEvidenceByID :one
SELECT id, user_id, filename, original_name, mime_type, file_size, description, latitude, longitude, created_at FROM evidence
WHERE id = $1
`

func (q *Queries) GetEvidenceByID(ctx context.Context, id uuid.UUID) (Evidence, error) {
	row := q.db.QueryRow(ctx, getEvidenceByID, id)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.FileSize,
		&i.Description,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
	)
	return i, err
}

const listEvidenceByUser = `-- name: ListEvidenceByUser :many
SELECT id, user_id, filename, original_name, mime_type, file_size, description, latitude, longitude, created_at FROM evidence
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEvidenceByUser(ctx context.Context, userID uuid.UUID) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidenceByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evidence
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.OriginalName,
			&i.MimeType,
			&i.FileSize,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
