// Code generated by sqlc. DO NOT EDIT.
// Regenerate with: make generate

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (sender_id, recipient_id, content, delivered)
VALUES ($1, $2, $3, $4)
RETURNING id, sender_id, recipient_id, content, delivered, created_at
`

type CreateMessageParams struct {
	SenderID    uuid.UUID `json:"sender_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
	Content     string    `json:"content"`
	Delivered   bool      `json:"delivered"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.SenderID, arg.RecipientID, arg.Content, arg.Delivered)
	var i Message
	err := row.Scan(&i.ID, &i.SenderID, &i.RecipientID, &i.Content, &i.Delivered, &i.CreatedAt)
	return i, err
}

// MessageWithSender extends Message with the sender's username resolved via JOIN.
type MessageWithSender struct {
	ID             uuid.UUID `json:"id"`
	SenderID       uuid.UUID `json:"sender_id"`
	RecipientID    uuid.UUID `json:"recipient_id"`
	Content        string    `json:"content"`
	Delivered      bool      `json:"delivered"`
	CreatedAt      time.Time `json:"created_at"`
	SenderUsername string    `json:"sender_username"`
}

const getMessagesBetweenUsers = `-- name: GetMessagesBetweenUsers :many
SELECT m.id, m.sender_id, m.recipient_id, m.content, m.delivered, m.created_at, u.username AS sender_username
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE (m.sender_id = $1 AND m.recipient_id = $2)
   OR (m.sender_id = $2 AND m.recipient_id = $1)
ORDER BY m.created_at ASC
`

type GetMessagesBetweenUsersParams struct {
	SenderID    uuid.UUID `json:"sender_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) GetMessagesBetweenUsers(ctx context.Context, arg GetMessagesBetweenUsersParams) ([]MessageWithSender, error) {
	rows, err := q.db.Query(ctx, getMessagesBetweenUsers, arg.SenderID, arg.RecipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []MessageWithSender
	for rows.Next() {
		var i MessageWithSender
		if err := rows.Scan(&i.ID, &i.SenderID, &i.RecipientID, &i.Content, &i.Delivered, &i.CreatedAt, &i.SenderUsername); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getUndeliveredMessages = `-- name: GetUndeliveredMessages :many
SELECT m.id, m.sender_id, m.recipient_id, m.content, m.delivered, m.created_at, u.username AS sender_username
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.recipient_id = $1 AND m.delivered = FALSE
ORDER BY m.created_at ASC
`

func (q *Queries) GetUndeliveredMessages(ctx context.Context, recipientID uuid.UUID) ([]MessageWithSender, error) {
	rows, err := q.db.Query(ctx, getUndeliveredMessages, recipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []MessageWithSender
	for rows.Next() {
		var i MessageWithSender
		if err := rows.Scan(&i.ID, &i.SenderID, &i.RecipientID, &i.Content, &i.Delivered, &i.CreatedAt, &i.SenderUsername); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const markMessageDelivered = `-- name: MarkMessageDelivered :exec
UPDATE messages SET delivered = TRUE WHERE id = $1
`

func (q *Queries) MarkMessageDelivered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMessageDelivered, id)
	return err
}

const markAllMessagesDelivered = `-- name: MarkAllMessagesDelivered :exec
UPDATE messages SET delivered = TRUE
WHERE recipient_id = $1 AND delivered = FALSE
`

func (q *Queries) MarkAllMessagesDelivered(ctx context.Context, recipientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllMessagesDelivered, recipientID)
	return err
}
