// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlcdb

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (sender_id, recipient_id, content, delivered)
VALUES ($1, $2, $3, $4)
RETURNING id, sender_id, recipient_id, content, delivered, created_at
`

type CreateMessageParams struct {
	SenderID    uuid.UUID `json:"sender_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
	Content     string    `json:"content"`
	Delivered   bool      `json:"delivered"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.SenderID,
		arg.RecipientID,
		arg.Content,
		arg.Delivered,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Content,
		&i.Delivered,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesBetweenUsers = `-- name: GetMessagesBetweenUsers :many
SELECT
    m.id, m.sender_id, m.recipient_id, m.content, m.delivered, m.created_at,
    u.username AS sender_username
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE (m.sender_id = $1 AND m.recipient_id = $2)
   OR (m.sender_id = $2 AND m.recipient_id = $1)
ORDER BY m.created_at ASC
`

type GetMessagesBetweenUsersParams struct {
	SenderID    uuid.UUID `json:"sender_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

type GetMessagesBetweenUsersRow struct {
	ID             uuid.UUID `json:"id"`
	SenderID       uuid.UUID `json:"sender_id"`
	RecipientID    uuid.UUID `json:"recipient_id"`
	Content        string    `json:"content"`
	Delivered      bool      `json:"delivered"`
	CreatedAt      time.Time `json:"created_at"`
	SenderUsername string    `json:"sender_username"`
}

func (q *Queries) GetMessagesBetweenUsers(ctx context.Context, arg GetMessagesBetweenUsersParams) ([]GetMessagesBetweenUsersRow, error) {
	rows, err := q.db.Query(ctx, getMessagesBetweenUsers, arg.SenderID, arg.RecipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesBetweenUsersRow
	for rows.Next() {
		var i GetMessagesBetweenUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.Delivered,
			&i.CreatedAt,
			&i.SenderUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUndeliveredMessages = `-- name: GetUndeliveredMessages :many
SELECT
    m.id, m.sender_id, m.recipient_id, m.content, m.delivered, m.created_at,
    u.username AS sender_username
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.recipient_id = $1 AND m.delivered = FALSE
ORDER BY m.created_at ASC
`

type GetUndeliveredMessagesRow struct {
	ID             uuid.UUID `json:"id"`
	SenderID       uuid.UUID `json:"sender_id"`
	RecipientID    uuid.UUID `json:"recipient_id"`
	Content        string    `json:"content"`
	Delivered      bool      `json:"delivered"`
	CreatedAt      time.Time `json:"created_at"`
	SenderUsername string    `json:"sender_username"`
}

func (q *Queries) GetUndeliveredMessages(ctx context.Context, recipientID uuid.UUID) ([]GetUndeliveredMessagesRow, error) {
	rows, err := q.db.Query(ctx, getUndeliveredMessages, recipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUndeliveredMessagesRow
	for rows.Next() {
		var i GetUndeliveredMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.Content,
			&i.Delivered,
			&i.CreatedAt,
			&i.SenderUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllMessagesDelivered = `-- name: MarkAllMessagesDelivered :exec
UPDATE messages SET delivered = TRUE
WHERE recipient_id = $1 AND delivered = FALSE
`

func (q *Queries) MarkAllMessagesDelivered(ctx context.Context, recipientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllMessagesDelivered, recipientID)
	return err
}

const markMessageDelivered = `-- name: MarkMessageDelivered :exec
UPDATE messages SET delivered = TRUE WHERE id = $1
`

func (q *Queries) MarkMessageDelivered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMessageDelivered, id)
	return err
}
